<a href="https://colab.research.google.com/github/absolution-end/GAN-Generative-Artificial-Intelligence-/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]],
     [[5, 6], [7, 8]],
     [[9, 0], [1, 2]]
    ]
)

In [4]:
example_tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

Tensor Properties

In [5]:
#Tensor device
example_tensor.device

device(type='cpu')

In [6]:
example_tensor.shape

torch.Size([3, 2, 2])

In [7]:
print("shape[0]=", example_tensor.shape[0])
print("Tensor size", example_tensor.size(1))

shape[0]= 3
Tensor size 2


In [8]:
print("Rank", len(example_tensor.shape))
print("Number of elements", example_tensor.numel())

Rank 3
Number of elements 12


Indexing Tensors

In [9]:
# To access nth element you can just type examplr_tensor[n]
example_tensor[1]

tensor([[5., 6.],
        [7., 8.]])

In [10]:
# If you wanted to access jth element in ith row you can type
example_tensor[1,1,1]

tensor(8.)

In [11]:
# If you want sclar value from tensor you can use
example_scalar = example_tensor[0,1,1]
example_scalar.item()

4.0

In [12]:
# if you want left elemet of each row you can type
example_tensor[:,0,0]

tensor([1., 5., 9.])

There are many ways to create tensor but in this course we will be focusing on the most important ones:

In [13]:
# torch.one_like: create tensor of all ones with the same shape and device as example tensor.
torch.ones_like(example_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [14]:
torch.zeros_like(example_tensor)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [15]:
torch.randn_like(example_tensor)

tensor([[[ 0.2287, -2.5633],
         [ 0.7823, -0.3218]],

        [[ 0.1252,  0.4425],
         [-0.1076, -0.7846]],

        [[ 0.0194, -0.5446],
         [ 0.0952, -0.8156]]])

In [16]:
# one can create tensor with just knowing shape and device of without a tensor for a refrence for one.likes, zero.likes and randn_likes etc.
torch.randn(4,4, 4, device='cpu')
# Alternatively, for GPU tensor, you'd use device='cuda'

tensor([[[ 0.0158, -1.0861,  0.9681, -0.8315],
         [ 1.8889,  0.8312,  2.1752,  0.9364],
         [ 0.2793,  0.0550, -0.7327, -0.6363],
         [ 0.4245, -0.3809, -0.4979,  0.5038]],

        [[-0.0148, -0.2667,  1.3082,  0.4039],
         [-1.0548,  1.3085, -0.9544,  2.0091],
         [ 1.5289,  0.9508,  0.5424,  0.3159],
         [-0.6354, -1.4152,  1.3646,  0.3915]],

        [[ 0.5137, -0.6044,  0.5334,  1.8360],
         [-1.6103, -1.8859, -0.3433,  0.3298],
         [-0.6107, -0.5942,  1.1547,  0.9740],
         [-0.3924,  1.7235, -0.1710,  0.5162]],

        [[-0.2904,  0.7228, -0.9276, -0.0861],
         [-1.0101, -0.2936,  1.0071, -0.7151],
         [ 0.0267,  0.7637, -0.2713, -0.3038],
         [-0.8279, -1.0856,  1.7965,  1.7791]]])

Basic functions as in numpy (+,-,*,/)

In [17]:
(example_tensor - 5)*5

tensor([[[-20., -15.],
         [-10.,  -5.]],

        [[  0.,   5.],
         [ 10.,  15.]],

        [[ 20., -25.],
         [-20., -15.]]])

In [18]:
# can calculate mean or standard deviation of tensor using example_tensor.mean() or example_tensor.std()
print("mean", example_tensor.mean())
print("standard deviation", example_tensor.std())

mean tensor(4.)
standard deviation tensor(2.9848)


In [19]:
# You might also want to find the mean or standard deviation along a particular dimension. To do this you can simple pass the number corresponding to that dimension to the function. For example, if you want to get the average  2×2
# matrix of the  3×2×2
# example_tensor you can write:

example_tensor.mean(0)

# Equivalently, you could also write:
# example_tensor.mean(dim=0)
# example_tensor.mean(axis=0)
# torch.mean(example_tensor, 0)
# torch.mean(example_tensor, dim=0)
# torch.mean(example_tensor, axis=0)


tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])

Pytorch neural network model

In [20]:
import torch.nn as nn

To create neural network linear layer nn.Linear

In [21]:
# to create a linear layer you need to pass the number of input dimentions and number of output dimentions
# nn.Linear(10,2)--> we will take n x 10 matrx and 2 x n matrix
# where all n have the same linear transformation
# linear layer perfroms Ax + B operations

In [22]:
Linear = nn.Linear(10,2)
example_input = torch.randn(3,10)
example_output = Linear(example_input)
example_output

tensor([[-0.7137, -0.2874],
        [-0.7680, -0.4531],
        [-0.4101,  1.0905]], grad_fn=<AddmmBackward0>)

ReLU --> mean non-zero numbers

In [23]:
  relu = nn.ReLU()
  relu_output = relu(example_output)
  relu_output

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 1.0905]], grad_fn=<ReluBackward0>)

**nn.BatchNorm1d**

nn.BatchNorm1d is a normalization technique that will rescale a batch of  𝑛
  inputs to have a consistent mean and standard deviation between batches.

As indicated by the 1d in its name, this is for situations where you expect a set of inputs, where each of them is a flat list of numbers. In other words, each input is a vector, not a matrix or higher-dimensional tensor. For a set of images, each of which is a higher-dimensional tensor, you'd use nn.BatchNorm2d, discussed later on this page.

nn.BatchNorm1d takes an argument of the number of input dimensions of each object in the batch (the size of each example vector).

In [24]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output =batchnorm(relu_output)
batchnorm_output

tensor([[ 0.0000, -0.7071],
        [ 0.0000, -0.7071],
        [ 0.0000,  1.4142]], grad_fn=<NativeBatchNormBackward0>)

**nn.Sequential**

nn.Sequential creates a single operation that performs a sequence of operations. For example, you can write a neural network layer with a batch normalization as



In [25]:
mlp_layer = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

test_example = torch.randn(5,5) + 1
print("input: ")
print(test_example)
print("output: ")
print(mlp_layer(test_example))

input: 
tensor([[ 0.5617,  0.2386,  0.0513,  0.1183, -0.7730],
        [ 2.3384,  0.1083,  0.5582,  1.6016,  1.2227],
        [ 1.1525,  0.7474,  2.0256,  0.9019, -0.0505],
        [ 2.5681, -0.8107,  2.3292, -0.3438,  1.0129],
        [ 2.2647,  1.1892,  0.5103,  0.6676,  0.7877]])
output: 
tensor([[0.0000, 1.7783],
        [0.5916, 0.0000],
        [1.0937, 0.0000],
        [0.0000, 0.3761],
        [0.6263, 0.0000]], grad_fn=<ReluBackward0>)


**Optimization**

One of the most important aspects of essentially any machine learning framework is its automatic differentiation library.

**Optimizers**

To create an optimizer in PyTorch, you'll need to use the torch.optim module, often imported as optim. optim.Adam corresponds to the Adam optimizer. To create an optimizer object, you'll need to pass it the parameters to be optimized and the learning rate, lr, as well as any other parameters specific to the optimizer.

For all nn objects, you can access their parameters as a list using their parameters() method, as follows:

Optimization in machine learning uses automatic differentiation to update model parameters. In PyTorch, the torch.optim module provides optimizers like optim.Adam. To use it, pass the model parameters and a learning rate (lr) to the optimizer. You can get these parameters from any neural network (nn) object using the parameters() method.









In [26]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(), lr=1e+1)

Training Loop
A (basic) training step in PyTorch consists of four basic parts:



1.  Set all of the gradients to zero using opt.zero_grad()
2.  Calculate the loss, loss
1.  Calculate the gradients with respect to the loss using loss.backward()
2.  Update the parameters being optimized using opt.step()

That might look like the following code (and you'll notice that if you run it several times, the loss goes down):

In [27]:
train_example = torch.randn(100,5)  +  1
adam_opt.zero_grad()
# we will use a simple loss function of mean distance 1
# torch.abs takes the absolute value of a tensor
cur_loss = torch.abs(1 - mlp_layer(train_example)).mean()
cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7728, grad_fn=<MeanBackward0>)


**requires_grad_()**

You can also tell PyTorch that it needs to calculate the gradient with respect to a tensor that you created by saying example_tensor.requires_grad_(), which will change it in-place. This means that even if PyTorch wouldn't normally store a grad for that particular tensor, it will for that specified tensor.

**with torch.no_grad():**

PyTorch will usually calculate the gradients as it proceeds through a set of operations on tensors. This can often take up unnecessary computations and memory, especially if you're performing an evaluation. However, you can wrap a piece of code with with torch.no_grad() to prevent the gradients from being calculated in a piece of code.

**detach():**

Sometimes, you want to calculate and use a tensor's value without calculating its gradients. For example, if you have two models, A and B, and you want to directly optimize the parameters of A with respect to the output of B, without calculating the gradients through B, then you could feed the detached output of B to A. There are many reasons you might want to do this, including efficiency or cyclical dependencies (i.e. A depends on B depends on A).

**New nn Classes**

You can also create new classes which extend the nn module. For these classes, all class attributes, as in self.layer or self.param will automatically treated as parameters if they are themselves nn objects or if they are tensors wrapped in nn.Parameter which are initialized with the class.

The __init__ function defines what will happen when the object is created. The first line of the init function of a class, for example, WellNamedClass, needs to be super(WellNamedClass, self).__init__().

The forward function defines what runs if you create that object model and pass it a tensor x, as in model(x). If you choose the function signature, (self, x), then each call of the forward function, gets two pieces of information: self, which is a reference to the object with which you can access all of its parameters, and x, which is the current tensor for which you'd like to return y.

In [28]:
class ExampleModule(nn.Module):
    def __init__(self, input_dims, output_dims):
        super(ExampleModule, self).__init__()
        self.linear = nn.Linear(input_dims, output_dims)
        self.exponent = nn.Parameter(torch.tensor(1.))

    def forward(self, x):
        x = self.linear(x)

        # This is the notation for element-wise exponentiation,
        # which matches python in general
        x = x ** self.exponent

        return x

In [29]:
example_model = ExampleModule(10,2)
list(example_model.parameters())

[Parameter containing:
 tensor(1., requires_grad=True),
 Parameter containing:
 tensor([[-0.2579, -0.1268, -0.0090, -0.2341,  0.0105, -0.2143,  0.1342, -0.1686,
          -0.1353, -0.1899],
         [ 0.0344,  0.2634,  0.2609,  0.2903, -0.0438, -0.0649,  0.1619,  0.1334,
          -0.0815,  0.2821]], requires_grad=True),
 Parameter containing:
 tensor([-0.2286,  0.0875], requires_grad=True)]

In [30]:
list(example_model.named_parameters())

[('exponent',
  Parameter containing:
  tensor(1., requires_grad=True)),
 ('linear.weight',
  Parameter containing:
  tensor([[-0.2579, -0.1268, -0.0090, -0.2341,  0.0105, -0.2143,  0.1342, -0.1686,
           -0.1353, -0.1899],
          [ 0.0344,  0.2634,  0.2609,  0.2903, -0.0438, -0.0649,  0.1619,  0.1334,
           -0.0815,  0.2821]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([-0.2286,  0.0875], requires_grad=True))]

In [31]:
input = torch.randn(2,10)
example_model(input)

tensor([[-0.8105,  0.5930],
        [ 0.4082,  0.3206]], grad_fn=<PowBackward1>)

**2D Operations**

You won't need these for the first lesson, and the theory behind each of these will be reviewed more in later lectures, but here is a quick reference:

2D convolutions: nn.Conv2d requires the number of input and output channels, as well as the kernel size.
2D transposed convolutions (aka deconvolutions): nn.ConvTranspose2d also requires the number of input and output channels, as well as the kernel size
2D batch normalization: nn.BatchNorm2d requires the number of input dimensions
Resizing images: nn.Upsample requires the final size or a scale factor. Alternatively, nn.functional.interpolate takes the same arguments.